---
- name: Disable SELinux permanently and reboot
  hosts: managers
  become: yes
  tasks:

    - name: Disable SELinux immediately (set permissive mode)
      command: setenforce 0
      ignore_errors: yes

    - name: Update SELinux config file
      replace:
        path: /etc/selinux/config
        regexp: '^SELINUX=.*'
        replace: 'SELINUX=disabled'

    - name: Reboot the server
      reboot:
        msg: "Reboot initiated by Ansible after disabling SELinux"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
