---
- name: Open firewall ports
  hosts: managers
  become: yes
  tasks:

    - name: Open HTTP ports
      ansible.posix.firewalld:
        port: "{{ item }}/tcp"
        permanent: yes
        state: enabled
      with_items:
        - 9100

    - name: Reload firewalld to apply changes
      ansible.builtin.service:
        name: firewalld
        state: reloaded
