---
- name: Install Grafana
  hosts: nginx_server
  become: yes
  tasks:

    - name: Add Grafana repo
      yum_repository:
        name: grafana
        description: Grafana repo
        baseurl: https://packages.grafana.com/oss/rpm
        gpgcheck: yes
        gpgkey: https://packages.grafana.com/gpg.key
        enabled: yes

    - name: Install Grafana
      yum:
        name: grafana
        state: present

    - name: Enable and start Grafana
      systemd:
        name: grafana-server
        enabled: yes
        state: started
